version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony-network

  php:
    #image: php:8-fpm
    build:
      context: docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ./:/var/www
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - database
    networks:
      - symfony-network

  database:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge

volumes:
  mysql-data:
